FROM ubuntu

RUN apt update

ARG URL=http://169.44.201.108:7002/jetpacks/4.3
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt install -y \
	python3.6 \
	python3-pip \
        python-opencv \
        python3-opencv \
        vim-tiny \
        mosquitto-clients \
        libopencv-dev
RUN pip3 install paho-mqtt

WORKDIR /HW03
