FROM alpine

# build this: e.g docker build -t motion -f Dockerfile.opencv-mqtt
# to run this container, do:
# on the host:
# make sure you're in the X environment
# xhost + 
# docker run --rm --privileged -e DISPLAY -v /tmp:/tmp -ti motion bash

RUN apk update

RUN apk add mosquitto-clients

RUN apk add --update py-pip

RUN pip install paho-mqtt

WORKDIR /
