FROM alpine

# build this: e.g docker build -t motion -f Dockerfile.opencv-mqtt
# to run this container, do:
# on the host:
# make sure you're in the X environment
# xhost + 
# docker run --rm --privileged -e DISPLAY -v "$PWD":/hw03 --name mosquitto_broker -ti alpine_mosquitto bash

RUN apk update

RUN apk add mosquitto

WORKDIR /
